name: CI
on:
  push:
  pull_request:
    branches: develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Run build
      run: npm run build

  test:
    runs-on: ubuntu-latest
    container: node:21-bookworm

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm run test:cov
    - name: Export coverage
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./coverage/lcov-report
